{
   "namespace":"example.avro",
   "type":"record",
   "name":"Endereco",
   "fields":[
      {
         "name":"logradouro",
         "type":[
            "string",
            "null"
         ]
      },
      {
         "name":"numero",
         "type":[
            "int",
            "null"
         ]
      },
      {
         "name":"cidade",
         "type":[
            "string",
            "null"
         ]
      },
      {
         "name":"estado",
         "type":[
            "string",
            "null"
         ]
      },
      {
         "name":"cep",
         "type":[
            "string",
            "null"
         ]
      }
   ]
}
